polimediaupv/paella

config/config.json
doc/integrate_basic.md
paella-standalone.js

There is a typo in the config parameter for the example repository, this fixes it.

Fixed reposiroty typo

---

src/06_ui_controls.js
src/09_paella_player.js

paella.PlayerBase.initialize takes a playerId as the first argument.
This allows changing the id and in theory would allow multiple players
in one document. This id is used in a lot of places to construct unique
ids, but there are some places that expect a container with the id
`playerContainer`.
This tries to fix this. setupTimeOnly and setupTimeImageOverlay may
need further attention as they completely ignore the existing
paella.DomNode facilities.

Remove dependencies on #playerContainer id

---

javascript/base.js

When setting parameters without using URLs it is helpful if
`base.parameters.list` is always an object.
As lookups in `base.parameters.get` don’t differ, there should be no
reason to create an array here.

Always init parameters as object

---

src/06_ui_controls.js

`real` is not used in these functions. `videoContainer.duration` is
also a function that should be called to get the duration.

Remove unneeded code

---

plugins/es.upv.paella.TrimmingPlugins/trimming_editor.js

This bug on the trimming plugin editor was not obvious. It is visible when changing between editor/player views. Particularly:
1. Open the editor, do some changes, save and close. (Without reloading the page)
2. Open the editor again, do some changes (or not) and exit using the 'Discard changes' option. (Again without reloading)
3. Open the editor once more:
The trimming bar will be shown as it was when we first opened it, no changes shown. However, when reloading the changes we saved will show correctly.

Fixed editor not displaying saved changes on trimming.

---

plugins/es.upv.paella.breakPlugins/editor.js

After leaving the editor using 'Discard changes' and entering  the editor again the discarded changes would still appear (although they wouldn't be saved if closing the browser)
I added a 'backup' for the breaks and implemented onDiscard to restore the last saved changes in the case the user decides to 'Discard'.

Fixed editor not discarding changes on Breaks plugin

---

plugins/es.upv.paella.breakPlugins/player.js

This value, if set to true, will hide the breaks not showing you the text and jumping to the end of any break if the player time is set inside it.
Otherwise, it behaves as usual.

Added config value 'neverShow' to the breaksPlayer plugin.

---

plugins/es.upv.paella.breakPlugins/player.js

Even if the configuration value 'neverShow' is 'true', the behaviour on the editor should remain before
* Added a function 'areBreaksClickable' to check if breaks should be skipped or not if clicked.
* Added check in case the paella.editor.instance exists and 'isLoaded' is true.

Added check to breaksPlugin/player.js in case the editor is activated.

---

plugins/es.upv.paella.fullScreenButtonPlugin/fullscreenbutton.js

This bugfix solves an small issue when redirecting a mobile user to a "fullscreen" player.
The issue is basically due to the player attaching the extra url parameters with an "&", not having into account whether the url had any parameter to begin with (which in our case does not)

Bugfix: mobile fullscreen

---

plugins/es.upv.paella.fullScreenButtonPlugin/fullscreenbutton.js

There was an error in the last pull request (#203).
indexOf() returns "-1" when the string is not found, which it is a true-like value, thus the ternary operator always returned "&".

Bugfix: Fix mobile fullscreen

---

src/04_video_container.js

If the `paella.VideoLoader` doesn't provide the resolution the media,
the player stops because cannot read property 'w' of undefined.

Fix bug when not resolution in BestFitVideoQualityStrategy

---

resources/style/controls.less

@vgoya misses the shadow. In Paella 5.x the video element has not the video class. 
*without-shadow*:
*with-shadow*:

Fix CSS to use box-shadow into the video element

---

plugins/es.upv.paella.breakPlugins/player.js

Fixes #257 .
- Check the videoContainer `trimStart` when `seekToTime` in the `breakPlugin`.

#257 Bracks don't end at the correct time with trimmed video

---

plugins/es.upv.paella.volumeRangePlugin/volumeRange.less

Bug:
-Add a cross-browser styling to volume slider.

Volume slider in Safari doesn't show properly

---

src/06_ui_controls.js

Fixes UX .
- Not hide UI controls if cursor is over it like Youtube player and others.
I really hate the default paella player behaviour.

UX: Not hide UI controls if cursor is over it

---

src/04_video_container.js

Fixes #  (a problem with choosing master as the mainAudioPlayer during  setAudioLanguage() )
- The setAudioLanguage() is currently choosing the last stream in the set of players to be the "this._audioPlayer" which is usually the last slave. The "master" video is usually the first in the array but the loop choose the last to be the audioPlayer.
- This pull adds the (!audioSet) to prevent selecting another audioPlayer after the first (the master) is found. 
- The current code sets "audioSet" to false right before the audioPlayer selection loop, so the omission of the audioSet check appears to be an existing bug.

Fix for Master video (first in stream array) as  mainAudioPlayer during setAudioLanguage

---

plugins/es.upv.paella.videoZoom/video_zoom.less
src/03_video_nodes.js

Fixes #294
- add class name "freezeFrame" to the HTML5 freeze() canvas video overlay to  give it style.
- add style to ".freezeFrame" to prevent it being side aligned with the video that it needs to overlay during freeze() event in the Qualities toggle.
- correct the canvas ID to be a unique id by integrating with the video element ID
Note: adding freezeFrame style into the zoom  plugin css since this is where videoWrapper gets its flex CSS that affects the canvas (freezeFrame) overlay.

Qualities canvas overlay alignment and unique id fix

---

plugins/es.upv.paella.rtmpPlayer/rtmp_player.js

Fixes ability to toggle quality on live stream events that have multiple source qualities. (HUDCE sends 2 rtmp stream qualities for live events to allow user to toggle resolution)
- add "streamName" parameter to rtmp video element object to help identify sources of same type during quality toggle.
- allow rtmp live event source to reload when its quality index has changed.

Quality toggle fix for rtmp sources

---

src/05_plugin_base.js

Feature for feature request #291:Optionally pause onresize timer in PluginManager.
- Adds new PluginManager  attribute "doResize" that defaults to true
- PluginManager checks "doResize" attribute before calling onresize() in its timer.
- This attribute gives custom plugins the ability to call "paella.pluginManager.doResize = false;" before an activity that conflicts with onresize() activity. Then, "paella.pluginManager.doResize = true;" after the conflict has passed.

Feature request #291: Optional pause for onresize timer in PluginManager

---

plugins/es.upv.paella.captionsPlugin/overlayCaptionsPlugin.js

Steps to reproduce:
1.- Go to Paella Player captions video example.
2.- Inspect it and change the resolution to one below 600 px width.
3.- Reproduce it and wait until the controls bar hides.
Actual Behavior:
Most of the captions appear in two lines and the second line appears cut from below.
Expected Behavior:
It should show the second line complete. With only one line it does not occur.
Fixes #297

Captions with two lines get cut from below when the controls bar hides

---

plugins/es.upv.paella.videoZoom/video_zoom.less

Fixes #294  wonky video load on vertical browser when zoomVideo is disabled.
- remove global styling of videoWrapper class by zoomVideo plugin
- preserve videoZoomButton central align styling
- prevents wonky offset video load on vertical browsers when zoomVideo is disabled

issue294 videoWrapper vertical load

---

gulpfile.js
package.json

Fixes #320 .
- Use gulp-uglify-es 1.0.0 instead of gulp-uglify 2.0.0
The reason is that gulp-uglify (2.0.0 and also 3.0.0) does not support ES2015: According to https://github.com/terinjokes/gulp-uglify, it uses UglifyJS3 which according to https://github.com/mishoo/UglifyJS2 (don't mind the number "2" here, the page is for version 3) does only support ES5 (not ES6/ES2015).
So if you want to uglify the ES2015 version of the Paella player, gulp-uglify is not an option.
The resulting file sizes are comparable.

Switch to gulp-uglify-es 

---

plugins/es.upv.paella.breakPlugins/player.js

Bug: If the end of a video break is longer than video's duration the browser/tab crashes.
- If this occurs, the video is paused and sought to the start as if it have ended normally.

Fixed tab crash if break is longer than video

---

plugins/es.upv.paella.track4kPlugin/main.js
plugins/es.upv.paella.track4kPlugin/style.css

Fixed problems in processing trackhd.json file. 
Enabled auto-tracking to be turned on/off, while keeping the current view.
Added button to reset view.
Used red font color to mark if autotracking is on/off. Removed confusing camera icon, that replaced the zoom menu icon. I had a hard time to find out that the menu was not broken, when enabling auto-tracking.
Fixed selection of current zoom-frame after seeking, as now the last active frame is selected.

Track4k auto zoom fixes
